name: werewolf_arena
description: 狼人杀竞技场 - AI对战游戏
version: 2.0.0
repository: https://github.com/cals/werewolf_arena
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  args: ^2.4.2
  auto_route: ^10.1.2
  cli_spin: ^1.0.1
  get_it: ^8.0.3
  laconic:
    git: git@github.com:CalsRanna/laconic.git
  logger: ^2.6.2
  openai_dart: ^0.5.5
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.0
  signals: ^6.0.2
  sqlite3_flutter_libs: ^0.5.40
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.2.4
  build_runner: ^2.4.15
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "asset/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "asset/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "asset/icon.png"