name: werewolf_arena
description: 狼人杀竞技场 - AI对战游戏
version: 2.0.0
repository: https://github.com/cals/werewolf_arena

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # 现有依赖（保持兼容）
  http: ^1.1.0
  json_annotation: ^4.8.1
  logger: ^2.6.2
  args: ^2.4.2
  path: ^1.9.0
  yaml: ^3.1.2
  intl: ^0.19.0
  openai_dart: ^0.5.5
  flutter_gen: ^5.12.0
  cli_spin: ^1.0.1

  # Flutter核心依赖
  cupertino_icons: ^1.0.2
  auto_route: ^10.1.2
  get_it: ^8.0.3
  signals: ^6.0.2
  google_fonts: ^4.0.3
  cached_network_image: ^3.4.1
  animated_text_kit: ^4.2.2
  lottie: ^3.3.2
  shared_preferences: ^2.2.0
  window_manager: ^0.3.2
  tray_manager: ^0.2.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # 代码生成
  auto_route_generator: ^10.2.4
  build_runner: ^2.4.15
  json_serializable: ^6.7.1

  # 现有开发依赖
  lints: ^6.0.0
  test: ^1.25.6
  mocktail: ^0.3.0
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - asset/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "asset/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "asset/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "asset/icon.png"