# 狼人杀游戏核心配置
# 此配置文件包含游戏的基础UI和日志设置

# UI配置
ui:
  console_width: 80
  enable_colors: true
  enable_animations: true
  show_debug_info: false
  log_level: "info"

  display:
    show_player_status: true
    show_game_state: true
    show_action_history: true
    show_statistics: true

# 日志配置
logging:
  level: "info"
  enable_console: true
  enable_file: true
  log_file: "logs/werewolf_arena.log"
  max_file_size: "10MB"
  backup_count: 5

  format:
    timestamp: true
    level: true
    logger_name: false

# 开发配置
development:
  debug_mode: false
  step_by_step: false
  auto_start: true
  fast_mode: false

  testing:
    enable_mock_llm: false
    deterministic_random: false
    save_game_states: false