# LLM服务配置
# 此配置文件包含所有与语言模型相关的设置

# 默认LLM配置
default_llm:
  model: "deepseek/deepseek-chat-v3.1"
  api_key: "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"
  base_url: "https://openrouter.ai/api/v1"
  timeout_seconds: 30
  max_retries: 3

# 玩家特定模型配置
player_models:
  "1":
    model: "deepseek/deepseek-v3.2-exp"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

  "2":
    model: "anthropic/claude-sonnet-4.5"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

  "3":
    model: "deepseek/deepseek-chat-v3.1"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

  "4":
    model: "deepseek/deepseek-r1-0528"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

  "5":
    model: "deepseek/deepseek-chat-v3-0324"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

  "6":
    model: "anthropic/claude-sonnet-4"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

  "7":
    model: "anthropic/claude-3.5-sonnet"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

  "8":
    model: "openai/gpt-5"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

  "9":
    model: "openai/o3"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

  "10":
    model: "google/gemini-2.5-pro"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

  "11":
    model: "x-ai/grok-4"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

  "12":
    model: "qwen/qwen3-max"
    api_key: "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"
    base_url: "https://openrouter.ai/api/v1"
    timeout_seconds: 30
    max_retries: 3

# 提示词设置
prompts:
  enable_context: true
  strategy_hints: true
  personality_traits: true

  # 基础系统提示词模板（不包含具体板子信息）
  base_system_prompt: |
    你是狼人杀高手"逻辑链"，目标是带领你的阵营获胜。

    核心原则：
    - 完全沉浸角色，绝不暴露AI身份
    - 好人：找狼保神，逻辑清晰
    - 狼人：完美伪装，服从团队
    - 发言自然口语化，用"我觉得"、"盘一下"等表达
    - 禁用Markdown语法和括号注释

    游戏规则将根据当前场景动态配置。
    直接输出发言或决策，不要加"我的发言如下"等前缀。

# 通用LLM设置
llm_settings:
  temperature: 0.7
  max_tokens: 1000
  top_p: 0.9
  frequency_penalty: 0.0
  presence_penalty: 0.0